# @package _global_

gen_dataset:
  _target_: dataloader.dataloader.Dataset_

data:
  data_root_dir: ${work_dir}/data/
  data_root_dir_all : ${work_dir}/data/
  file_format: '*.file_extension'
  use_background_generator: false
  divide_dataset_per_gpu: false
  