# @package _global_

gen_dataset:
  _target_: dataloader.dataloader.Dataset_

data:
  data_root_dir: ${work_dir}/data/new_data/
  data_root_dir_all : ${work_dir}/data/new_data/
  data_root_dir_3d : ${work_dir}/data/data_3d/
  external_data: ${work_dir}/data/external/
  file_format: '*.file_extension'
  use_background_generator: false
  divide_dataset_per_gpu: false
  